spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductCategory?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


#  flyway:
#    url: jdbc:mysql://localhost:3306/ProductCategory
#    user: root
#    password:
#    baseline-on-migrate: true
#    locations: classpath:db/migration



#spring.jpa.properties.hibernate.connection.CharSet=utf8
#spring.jpa.properties.hibernate.connection.characterEncoding=utf8
#spring.jpa.properties.hibernate.connection.useUnicode=true

#server.tomcat.uri-encoding=UTF-8